language: node_js
node_js: 
    - "12"
install:
    - npm i
script:    
    - npm run build    
deploy: 
    - if: branch = master
      provider: npm
      email: $API_ACCOUNT
      api_key: $API_KEY